# version: '3.8'
# services:
#     php-apache-environment:
#         container_name: php-apache
#         build:
#             context: ./php-apache2
#             dockerfile: Dockerfile
#         depends_on:
#           - db
#         volumes:
#             - ./sources/:/var/www/html/
#         ports:
#             - 8000:80
            
#     db:
#         container_name: db
#         image: mysql
#         restart: always
#         environment:
#             MYSQL_ROOT_PASSWORD: mysql12345
#             MYSQL_DATABASE: selling_computer
#             MYSQL_USER: trannguyenhan
#             MYSQL_PASSWORD: mysql12345
#         ports:
#             - "9906:3306"
#         volumes: 
#             - ./sources/database/selling_computer.sql:/docker-entrypoint-initdb.d/dump.sql
